version: '3.9'
services:
  app:
    build: ./
    command: /app/NeverIdle -c 2h -m 2 -n 4h
    restart: always
    volumes:
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
