name: release

on:
  push:
    tags:
      - 'v*'
      - '[0-9]*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Build binaries
        env:
          CGO_ENABLED: '0'
        run: |
          # Linux amd64
          GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-s -w -buildid=" -o NeverIdle-linux-amd64 main.go
          # Linux arm64
          GOOS=linux GOARCH=arm64 go build -trimpath -ldflags="-s -w -buildid=" -o NeverIdle-linux-arm64 main.go
          # Windows amd64
          GOOS=windows GOARCH=amd64 go build -trimpath -ldflags="-s -w -buildid=" -o NeverIdle-windows-amd64.exe main.go

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v3
        with:
          files: |
            NeverIdle-linux-amd64
            NeverIdle-linux-arm64
            NeverIdle-windows-amd64.exe
          generate_release_notes: true
